"use client";

import { NextPage } from 'next';
import { Provider as ReduxProvider } from 'react-redux';
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline} from '@mui/material';
import Head from 'next/head';
import theme from '../theme/theme';
import React from "react";
import { store } from "@/redux/store";
import NavBar from "@/common/navBar";

import "../globals.css";

const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: NextPage<{ children: React.ReactNode }> = ({ children }) => {

    return (
        <html lang="en">
        <Head>
            <meta charSet="UTF-8" />
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
            <CssBaseline />
        </Head>
        <body>
        <ReduxProvider store={store}>
            <ThemeProvider theme={theme}>
                <NavBar/>
                {children}
            </ThemeProvider>
        </ReduxProvider>
        </body>
        </html>
    );
};

export default RootLayout;
